import os
import sys
# Add project root to sys.path so sibling packages (utils, services, etc.) are importable
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, log_loss

from utils.logger import logger


def train_pipeline(dataset_path: str = "ml/dataset_world_cup.csv"):
    """Train an XGBoost model on the international‑only dataset.

    Parameters
    ----------
    dataset_path: str
        Path to the CSV file generated by `build_dataset_world_cup.py`.
    """
    if not os.path.exists(dataset_path):
        logger.error(
            f"Dataset not found at {dataset_path}. Run `python -m ml.build_dataset_world_cup` first."
        )
        return

    logger.info(f"Loading dataset from {dataset_path} …")
    df = pd.read_csv(dataset_path)

    X = df.drop(columns=["target", "home_team", "away_team"])
    y = df["target"]

    logger.info(f"Dataset shape: {df.shape}")
    logger.info(f"Class distribution:\n{y.value_counts(normalize=True)}")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=5,
        learning_rate=0.05,
        objective="multi:softprob",
        num_class=3,
        eval_metric="mlogloss",
        random_state=42,
    )

    logger.info("Running 5‑fold cross‑validation …")
    cv_scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")
    logger.info(f"CV accuracy: {cv_scores}")
    logger.info(f"Mean CV accuracy: {np.mean(cv_scores):.4f} (+/- {np.std(cv_scores):.4f})")

    logger.info("Training final model …")
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)
    acc = accuracy_score(y_test, y_pred)
    loss = log_loss(y_test, y_prob)
    logger.info(f"Holdout Test Accuracy: {acc:.4f}")
    logger.info(f"Holdout Test Log Loss: {loss:.4f}")

    # Feature importance
    importances = model.feature_importances_
    features = X.columns
    indices = np.argsort(importances)[::-1]
    logger.info("=== Feature Importance ===")
    for rank, idx in enumerate(indices, start=1):
        logger.info(f"{rank}. {features[idx]:<15} – {importances[idx]:.4f}")

    models_dir = os.path.join(os.path.dirname(__file__), "models")
    os.makedirs(models_dir, exist_ok=True)
    model_path = os.path.join(models_dir, "xgboost_model_world_cup.json")
    logger.info(f"Saving model to {model_path} …")
    model.save_model(model_path)
    logger.info("Model saved successfully.")


if __name__ == "__main__":
    train_pipeline()
