"""Add SofaScore tables and columns

Revision ID: 89fe0513228c
Revises: 1ba737317132
Create Date: 2026-06-26 07:27:47.073848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import logging

logger = logging.getLogger('alembic')


# revision identifiers, used by Alembic.
revision: str = '89fe0513228c'
down_revision: Union[str, None] = '1ba737317132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Handle enums - use raw SQL to check existence and create IF NOT EXISTS
    def create_enum_if_not_exists(enum_name, enum_values):
        # Check if enum exists in PostgreSQL
        enum_exists = conn.execute(sa.text(f"""
            SELECT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = :enum_name
            )
        """), {"enum_name": enum_name}).scalar()
        
        if not enum_exists:
            # Create enum
            values_str = ', '.join([f"'{v}'" for v in enum_values])
            conn.execute(sa.text(f"CREATE TYPE {enum_name} AS ENUM ({values_str})"))
            logger.info(f"Created enum {enum_name} with values {enum_values}")
        else:
            logger.info(f"Enum {enum_name} already exists, skipping creation")
    
    # Create eventtype enum if not exists
    eventtype_values = ['GOAL', 'PENALTY_GOAL', 'OWN_GOAL', 'YELLOW_CARD', 'SECOND_YELLOW_CARD', 'RED_CARD', 'SUBSTITUTION', 'INJURY', 'VAR_CHECK']
    create_enum_if_not_exists('eventtype', eventtype_values)
    
    # Create suspensionstatus enum if not exists
    suspensionstatus_values = ['PENDING', 'OFFICIAL', 'APPEALED', 'RESOLVED']
    create_enum_if_not_exists('suspensionstatus', suspensionstatus_values)
    
    # Get all existing tables
    existing_tables = inspector.get_table_names()
    
    # Create tables only if they don't exist
    if 'match_events' not in existing_tables:
        op.create_table('match_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('match_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=True),
        sa.Column('type', sa.dialects.postgresql.ENUM(name='eventtype', create_type=False), nullable=False),
        sa.Column('minute', sa.Integer(), nullable=False),
        sa.Column('extra_minute', sa.Integer(), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('player_name', sa.String(length=100), nullable=True),
        sa.Column('player_id', sa.Integer(), nullable=True),
        sa.Column('assist_player_name', sa.String(length=100), nullable=True),
        sa.Column('assist_player_id', sa.Integer(), nullable=True),
        sa.Column('substitute_in_player_name', sa.String(length=100), nullable=True),
        sa.Column('substitute_in_player_id', sa.Integer(), nullable=True),
        sa.Column('sofa_score_id', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['assist_player_id'], ['players.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['substitute_in_player_id'], ['players.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        )
        
    # Get existing indexes for match_events
    match_events_indexes = [idx['name'] for idx in inspector.get_indexes('match_events')] if 'match_events' in existing_tables else []
    if 'ix_match_events_id' not in match_events_indexes:
        op.create_index(op.f('ix_match_events_id'), 'match_events', ['id'], unique=False)
    if 'ix_match_events_match_id' not in match_events_indexes:
        op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    if 'ix_match_events_minute' not in match_events_indexes:
        op.create_index(op.f('ix_match_events_minute'), 'match_events', ['minute'], unique=False)
    if 'ix_match_events_sofa_score_id' not in match_events_indexes:
        op.create_index(op.f('ix_match_events_sofa_score_id'), 'match_events', ['sofa_score_id'], unique=True)
    if 'ix_match_events_team_id' not in match_events_indexes:
        op.create_index(op.f('ix_match_events_team_id'), 'match_events', ['team_id'], unique=False)
    if 'ix_match_events_type' not in match_events_indexes:
        op.create_index(op.f('ix_match_events_type'), 'match_events', ['type'], unique=False)
        
    if 'match_lineups' not in existing_tables:
        op.create_table('match_lineups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('match_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('formation', sa.String(length=20), nullable=True),
        sa.Column('starting_xi', sa.Text(), nullable=True),
        sa.Column('substitutes', sa.Text(), nullable=True),
        sa.Column('coach_name', sa.String(length=100), nullable=True),
        sa.Column('sofa_score_id', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        )
        
    match_lineups_indexes = [idx['name'] for idx in inspector.get_indexes('match_lineups')] if 'match_lineups' in existing_tables else []
    if 'ix_match_lineups_id' not in match_lineups_indexes:
        op.create_index(op.f('ix_match_lineups_id'), 'match_lineups', ['id'], unique=False)
    if 'ix_match_lineups_match_id' not in match_lineups_indexes:
        op.create_index(op.f('ix_match_lineups_match_id'), 'match_lineups', ['match_id'], unique=False)
    if 'ix_match_lineups_sofa_score_id' not in match_lineups_indexes:
        op.create_index(op.f('ix_match_lineups_sofa_score_id'), 'match_lineups', ['sofa_score_id'], unique=False)
    if 'ix_match_lineups_team_id' not in match_lineups_indexes:
        op.create_index(op.f('ix_match_lineups_team_id'), 'match_lineups', ['team_id'], unique=False)
        
    if 'match_statistics' not in existing_tables:
        op.create_table('match_statistics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('match_id', sa.Integer(), nullable=False),
        sa.Column('home_possession', sa.Float(), nullable=True),
        sa.Column('away_possession', sa.Float(), nullable=True),
        sa.Column('home_shots', sa.Integer(), nullable=True),
        sa.Column('away_shots', sa.Integer(), nullable=True),
        sa.Column('home_shots_on_target', sa.Integer(), nullable=True),
        sa.Column('away_shots_on_target', sa.Integer(), nullable=True),
        sa.Column('home_corners', sa.Integer(), nullable=True),
        sa.Column('away_corners', sa.Integer(), nullable=True),
        sa.Column('home_expected_goals', sa.Float(), nullable=True),
        sa.Column('away_expected_goals', sa.Float(), nullable=True),
        sa.Column('home_fouls', sa.Integer(), nullable=True),
        sa.Column('away_fouls', sa.Integer(), nullable=True),
        sa.Column('home_offsides', sa.Integer(), nullable=True),
        sa.Column('away_offsides', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        )
        
    match_statistics_indexes = [idx['name'] for idx in inspector.get_indexes('match_statistics')] if 'match_statistics' in existing_tables else []
    if 'ix_match_statistics_id' not in match_statistics_indexes:
        op.create_index(op.f('ix_match_statistics_id'), 'match_statistics', ['id'], unique=False)
    if 'ix_match_statistics_match_id' not in match_statistics_indexes:
        op.create_index(op.f('ix_match_statistics_match_id'), 'match_statistics', ['match_id'], unique=False)
        
    if 'player_match_performances' not in existing_tables:
        op.create_table('player_match_performances',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('match_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=True),
        sa.Column('player_name', sa.String(length=100), nullable=False),
        sa.Column('rating', sa.Float(), nullable=True),
        sa.Column('position', sa.String(length=50), nullable=True),
        sa.Column('is_starter', sa.Integer(), nullable=True),
        sa.Column('minutes_played', sa.Integer(), nullable=True),
        sa.Column('goals', sa.Integer(), nullable=True),
        sa.Column('assists', sa.Integer(), nullable=True),
        sa.Column('shots', sa.Integer(), nullable=True),
        sa.Column('shots_on_target', sa.Integer(), nullable=True),
        sa.Column('passes', sa.Integer(), nullable=True),
        sa.Column('pass_accuracy', sa.Float(), nullable=True),
        sa.Column('tackles', sa.Integer(), nullable=True),
        sa.Column('interceptions', sa.Integer(), nullable=True),
        sa.Column('saves', sa.Integer(), nullable=True),
        sa.Column('fouls_committed', sa.Integer(), nullable=True),
        sa.Column('fouls_drawn', sa.Integer(), nullable=True),
        sa.Column('yellow_cards', sa.Integer(), nullable=True),
        sa.Column('red_cards', sa.Integer(), nullable=True),
        sa.Column('offsides', sa.Integer(), nullable=True),
        sa.Column('corners', sa.Integer(), nullable=True),
        sa.Column('sofa_score_id', sa.String(length=50), nullable=True),
        sa.Column('sofa_score_rating', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        )
        
    player_match_performances_indexes = [idx['name'] for idx in inspector.get_indexes('player_match_performances')] if 'player_match_performances' in existing_tables else []
    if 'ix_player_match_performances_id' not in player_match_performances_indexes:
        op.create_index(op.f('ix_player_match_performances_id'), 'player_match_performances', ['id'], unique=False)
    if 'ix_player_match_performances_match_id' not in player_match_performances_indexes:
        op.create_index(op.f('ix_player_match_performances_match_id'), 'player_match_performances', ['match_id'], unique=False)
    if 'ix_player_match_performances_player_id' not in player_match_performances_indexes:
        op.create_index(op.f('ix_player_match_performances_player_id'), 'player_match_performances', ['player_id'], unique=False)
    if 'ix_player_match_performances_sofa_score_id' not in player_match_performances_indexes:
        op.create_index(op.f('ix_player_match_performances_sofa_score_id'), 'player_match_performances', ['sofa_score_id'], unique=False)
    if 'ix_player_match_performances_team_id' not in player_match_performances_indexes:
        op.create_index(op.f('ix_player_match_performances_team_id'), 'player_match_performances', ['team_id'], unique=False)
        
    if 'suspension_history' not in existing_tables:
        op.create_table('suspension_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('suspension_id', sa.Integer(), nullable=False),
        sa.Column('old_status', sa.dialects.postgresql.ENUM(name='suspensionstatus', create_type=False), nullable=True),
        sa.Column('new_status', sa.dialects.postgresql.ENUM(name='suspensionstatus', create_type=False), nullable=False),
        sa.Column('changed_by', sa.String(length=100), nullable=True),
        sa.Column('reason', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['suspension_id'], ['suspensions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        )
        
    suspension_history_indexes = [idx['name'] for idx in inspector.get_indexes('suspension_history')] if 'suspension_history' in existing_tables else []
    if 'ix_suspension_history_id' not in suspension_history_indexes:
        op.create_index(op.f('ix_suspension_history_id'), 'suspension_history', ['id'], unique=False)
    if 'ix_suspension_history_suspension_id' not in suspension_history_indexes:
        op.create_index(op.f('ix_suspension_history_suspension_id'), 'suspension_history', ['suspension_id'], unique=False)
    
    # Add columns to matches table, check if they exist first
    match_columns = [col['name'] for col in inspector.get_columns('matches')]
    
    if 'sofa_score_id' not in match_columns:
        op.add_column('matches', sa.Column('sofa_score_id', sa.String(length=50), nullable=True))
    if 'home_formation' not in match_columns:
        op.add_column('matches', sa.Column('home_formation', sa.String(length=20), nullable=True))
    if 'away_formation' not in match_columns:
        op.add_column('matches', sa.Column('away_formation', sa.String(length=20), nullable=True))
    if 'home_possession' not in match_columns:
        op.add_column('matches', sa.Column('home_possession', sa.Float(), nullable=True))
    if 'away_possession' not in match_columns:
        op.add_column('matches', sa.Column('away_possession', sa.Float(), nullable=True))
    if 'home_expected_goals' not in match_columns:
        op.add_column('matches', sa.Column('home_expected_goals', sa.Float(), nullable=True))
    if 'away_expected_goals' not in match_columns:
        op.add_column('matches', sa.Column('away_expected_goals', sa.Float(), nullable=True))
        
    # Add index if not exists
    match_indexes = [idx['name'] for idx in inspector.get_indexes('matches')]
    if 'ix_matches_sofa_score_id' not in match_indexes:
        op.create_index(op.f('ix_matches_sofa_score_id'), 'matches', ['sofa_score_id'], unique=True)
        
    # Add columns to suspensions table
    suspension_columns = [col['name'] for col in inspector.get_columns('suspensions')]
    if 'sofa_score_id' not in suspension_columns:
        op.add_column('suspensions', sa.Column('sofa_score_id', sa.String(length=50), nullable=True))
    if 'source' not in suspension_columns:
        op.add_column('suspensions', sa.Column('source', sa.String(length=50), nullable=True))
    if 'status' not in suspension_columns:
        op.add_column('suspensions', sa.Column('status', sa.dialects.postgresql.ENUM(name='suspensionstatus', create_type=False), nullable=True))
    if 'matches_banned' not in suspension_columns:
        op.add_column('suspensions', sa.Column('matches_banned', sa.Integer(), nullable=True))
    if 'reason' not in suspension_columns:
        op.add_column('suspensions', sa.Column('reason', sa.String(length=255), nullable=True))
    if 'official_date' not in suspension_columns:
        op.add_column('suspensions', sa.Column('official_date', sa.Date(), nullable=True))
        
    suspension_indexes = [idx['name'] for idx in inspector.get_indexes('suspensions')]
    if 'ix_suspensions_sofa_score_id' not in suspension_indexes:
        op.create_index(op.f('ix_suspensions_sofa_score_id'), 'suspensions', ['sofa_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Get existing indexes first
    suspension_indexes = [idx['name'] for idx in inspector.get_indexes('suspensions')]
    if 'ix_suspensions_sofa_score_id' in suspension_indexes:
        op.drop_index(op.f('ix_suspensions_sofa_score_id'), table_name='suspensions')
    
    # Drop columns from suspensions table, check if they exist first
    suspension_columns = [col['name'] for col in inspector.get_columns('suspensions')]
    if 'official_date' in suspension_columns:
        op.drop_column('suspensions', 'official_date')
    if 'reason' in suspension_columns:
        op.drop_column('suspensions', 'reason')
    if 'matches_banned' in suspension_columns:
        op.drop_column('suspensions', 'matches_banned')
    if 'status' in suspension_columns:
        op.drop_column('suspensions', 'status')
    if 'source' in suspension_columns:
        op.drop_column('suspensions', 'source')
    if 'sofa_score_id' in suspension_columns:
        op.drop_column('suspensions', 'sofa_score_id')
        
    # Create national team indexes if they don't exist
    national_team_indexes = {
        'national_team_injuries': 'ix_national_team_injuries_team_id',
        'national_team_players': 'ix_national_team_players_team_id',
        'national_team_suspensions': 'ix_national_team_suspensions_team_id'
    }
    for table, index_name in national_team_indexes.items():
        try:
            table_indexes = [idx['name'] for idx in inspector.get_indexes(table)]
            if index_name not in table_indexes:
                op.create_index(index_name, table, ['team_id'], unique=False)
        except Exception as e:
            logger.warning(f"Could not check/create index {index_name} on {table}: {e}")
            
    # Drop index and columns from matches
    match_indexes = [idx['name'] for idx in inspector.get_indexes('matches')]
    if 'ix_matches_sofa_score_id' in match_indexes:
        op.drop_index(op.f('ix_matches_sofa_score_id'), table_name='matches')
        
    match_columns = [col['name'] for col in inspector.get_columns('matches')]
    if 'away_expected_goals' in match_columns:
        op.drop_column('matches', 'away_expected_goals')
    if 'home_expected_goals' in match_columns:
        op.drop_column('matches', 'home_expected_goals')
    if 'away_possession' in match_columns:
        op.drop_column('matches', 'away_possession')
    if 'home_possession' in match_columns:
        op.drop_column('matches', 'home_possession')
    if 'away_formation' in match_columns:
        op.drop_column('matches', 'away_formation')
    if 'home_formation' in match_columns:
        op.drop_column('matches', 'home_formation')
    if 'sofa_score_id' in match_columns:
        op.drop_column('matches', 'sofa_score_id')
        
    # Drop suspension_history
    try:
        suspension_history_indexes = [idx['name'] for idx in inspector.get_indexes('suspension_history')] if 'suspension_history' in inspector.get_table_names() else []
        if 'ix_suspension_history_suspension_id' in suspension_history_indexes:
            op.drop_index(op.f('ix_suspension_history_suspension_id'), table_name='suspension_history')
        if 'ix_suspension_history_id' in suspension_history_indexes:
            op.drop_index(op.f('ix_suspension_history_id'), table_name='suspension_history')
        if 'suspension_history' in inspector.get_table_names():
            op.drop_table('suspension_history')
    except Exception as e:
        logger.warning(f"Could not drop suspension_history: {e}")
        
    # Drop player_match_performances
    try:
        if 'player_match_performances' in inspector.get_table_names():
            player_match_performances_indexes = [idx['name'] for idx in inspector.get_indexes('player_match_performances')]
            if 'ix_player_match_performances_team_id' in player_match_performances_indexes:
                op.drop_index(op.f('ix_player_match_performances_team_id'), table_name='player_match_performances')
            if 'ix_player_match_performances_sofa_score_id' in player_match_performances_indexes:
                op.drop_index(op.f('ix_player_match_performances_sofa_score_id'), table_name='player_match_performances')
            if 'ix_player_match_performances_player_id' in player_match_performances_indexes:
                op.drop_index(op.f('ix_player_match_performances_player_id'), table_name='player_match_performances')
            if 'ix_player_match_performances_match_id' in player_match_performances_indexes:
                op.drop_index(op.f('ix_player_match_performances_match_id'), table_name='player_match_performances')
            if 'ix_player_match_performances_id' in player_match_performances_indexes:
                op.drop_index(op.f('ix_player_match_performances_id'), table_name='player_match_performances')
            op.drop_table('player_match_performances')
    except Exception as e:
        logger.warning(f"Could not drop player_match_performances: {e}")
        
    # Drop match_statistics
    try:
        if 'match_statistics' in inspector.get_table_names():
            match_statistics_indexes = [idx['name'] for idx in inspector.get_indexes('match_statistics')]
            if 'ix_match_statistics_match_id' in match_statistics_indexes:
                op.drop_index(op.f('ix_match_statistics_match_id'), table_name='match_statistics')
            if 'ix_match_statistics_id' in match_statistics_indexes:
                op.drop_index(op.f('ix_match_statistics_id'), table_name='match_statistics')
            op.drop_table('match_statistics')
    except Exception as e:
        logger.warning(f"Could not drop match_statistics: {e}")
        
    # Drop match_lineups
    try:
        if 'match_lineups' in inspector.get_table_names():
            match_lineups_indexes = [idx['name'] for idx in inspector.get_indexes('match_lineups')]
            if 'ix_match_lineups_team_id' in match_lineups_indexes:
                op.drop_index(op.f('ix_match_lineups_team_id'), table_name='match_lineups')
            if 'ix_match_lineups_sofa_score_id' in match_lineups_indexes:
                op.drop_index(op.f('ix_match_lineups_sofa_score_id'), table_name='match_lineups')
            if 'ix_match_lineups_match_id' in match_lineups_indexes:
                op.drop_index(op.f('ix_match_lineups_match_id'), table_name='match_lineups')
            if 'ix_match_lineups_id' in match_lineups_indexes:
                op.drop_index(op.f('ix_match_lineups_id'), table_name='match_lineups')
            op.drop_table('match_lineups')
    except Exception as e:
        logger.warning(f"Could not drop match_lineups: {e}")
        
    # Drop match_events
    try:
        if 'match_events' in inspector.get_table_names():
            match_events_indexes = [idx['name'] for idx in inspector.get_indexes('match_events')]
            if 'ix_match_events_type' in match_events_indexes:
                op.drop_index(op.f('ix_match_events_type'), table_name='match_events')
            if 'ix_match_events_team_id' in match_events_indexes:
                op.drop_index(op.f('ix_match_events_team_id'), table_name='match_events')
            if 'ix_match_events_sofa_score_id' in match_events_indexes:
                op.drop_index(op.f('ix_match_events_sofa_score_id'), table_name='match_events')
            if 'ix_match_events_minute' in match_events_indexes:
                op.drop_index(op.f('ix_match_events_minute'), table_name='match_events')
            if 'ix_match_events_match_id' in match_events_indexes:
                op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
            if 'ix_match_events_id' in match_events_indexes:
                op.drop_index(op.f('ix_match_events_id'), table_name='match_events')
            op.drop_table('match_events')
    except Exception as e:
        logger.warning(f"Could not drop match_events: {e}")
    # ### end Alembic commands ###
