import { MatchPrediction, TrophyProbability, IntelligenceInsight } from "./types";

export const MOCK_MATCHES: MatchPrediction[] = [
  {
    id: "m1",
    teamA: "Brazil",
    teamB: "Germany",
    teamACode: "BRA",
    teamBCode: "GER",
    date: "June 09, 2026",
    stage: "Group Stage • Group A",
    status: "LIVE",
    prediction: "Brazil Win",
    confidence: "High",
    probA: 52,
    probD: 25,
    probB: 23,
    venue: "MetLife Stadium, New York/New Jersey",
    attackA: 94,
    attackB: 83,
    defenceA: 89,
    defenceB: 81,
    midfieldA: 91,
    midfieldB: 88,
    xGA: 2.35,
    xGB: 1.45,
    xGAA: 0.85,
    xGAB: 1.25,
    possessionA: 58,
    possessionB: 42,
    shotsA: 16.2,
    shotsB: 11.4,
    shotsAllowedA: 8.1,
    shotsAllowedB: 13.5,
    cleanSheetA: 45,
    cleanSheetB: 28,
    bttsRateA: 38,
    bttsRateB: 54,
    recentFormA: ["W", "W", "W", "D", "W"],
    recentFormB: ["D", "W", "L", "W", "D"],
    fifaRankA: 5,
    fifaRankB: 11,
    eloRankA: 3,
    eloRankB: 12,
    squadValueA: "€1.25B",
    squadValueB: "€890M",
    restDaysA: 5,
    restDaysB: 4,
    fatigueA: 18,
    fatigueB: 35,
    injuriesA: ["Rodrygo (Thigh Strain)"],
    injuriesB: ["Marc-André ter Stegen (Knee)", "Kimmich (Adductor)"],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: ["Rodrygo"],
    missingKeyPlayersB: ["Kimmich", "Ter Stegen"],
    impactRatingA: "Minimal",
    impactRatingB: "Critical",
    h2hPreviousMeetings: 23,
    h2hWinsA: 13,
    h2hWinsB: 5,
    h2hDraws: 5,
    h2hGoalsA: 41,
    h2hGoalsB: 31,
    aiSummary: "Brazil’s aggressive transitional overloads and high athletic baseline outperform Germany's aging defensive midblock. The numerical model registers high central penetrability for Germany, signaling a sustained territorial and chance creation edge for Brazil."
  },
  {
    id: "m2",
    teamA: "Argentina",
    teamB: "France",
    teamACode: "ARG",
    teamBCode: "FRA",
    date: "June 09, 2026",
    stage: "Group Stage • Group C",
    status: "UPCOMING",
    prediction: "Draw / Argentina Lean",
    confidence: "Medium",
    probA: 39,
    probD: 34,
    probB: 27,
    venue: "Rose Bowl, Los Angeles",
    attackA: 92,
    attackB: 95,
    defenceA: 91,
    defenceB: 90,
    midfieldA: 93,
    midfieldB: 89,
    xGA: 1.95,
    xGB: 2.10,
    xGAA: 0.90,
    xGAB: 1.05,
    possessionA: 53,
    possessionB: 47,
    shotsA: 13.8,
    shotsB: 14.2,
    shotsAllowedA: 9.2,
    shotsAllowedB: 10.1,
    cleanSheetA: 50,
    cleanSheetB: 40,
    bttsRateA: 45,
    bttsRateB: 48,
    recentFormA: ["W", "W", "W", "W", "D"],
    recentFormB: ["W", "D", "W", "L", "W"],
    fifaRankA: 1,
    fifaRankB: 2,
    eloRankA: 1,
    eloRankB: 2,
    squadValueA: "€950M",
    squadValueB: "€1.35B",
    restDaysA: 6,
    restDaysB: 6,
    fatigueA: 15,
    fatigueB: 12,
    injuriesA: ["Lisandro Martínez (Ankle Sprain)"],
    injuriesB: ["Eduardo Camavinga (Hamstring Strike)"],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: ["Lisandro Martínez"],
    missingKeyPlayersB: ["Camavinga"],
    impactRatingA: "Moderate",
    impactRatingB: "Moderate",
    h2hPreviousMeetings: 13,
    h2hWinsA: 6,
    h2hWinsB: 4,
    h2hDraws: 3,
    h2hGoalsA: 19,
    h2hGoalsB: 15,
    aiSummary: "A rerun of elite football giants. Fully balanced and dense midfields. While France holds an elite vertical pace profile, Argentina's unmatched possession retention rates and low defensive block efficiency neutralize transitional risks, pointing strongly toward a low-margin tactical draw."
  },
  {
    id: "m3",
    teamA: "Spain",
    teamB: "England",
    teamACode: "ESP",
    teamBCode: "ENG",
    date: "June 10, 2026",
    stage: "Group Stage • Group F",
    status: "UPCOMING",
    prediction: "Spain Win",
    confidence: "High",
    probA: 46,
    probD: 31,
    probB: 23,
    venue: "Estadio Azteca, Mexico City",
    attackA: 90,
    attackB: 89,
    defenceA: 88,
    defenceB: 85,
    midfieldA: 95,
    midfieldB: 92,
    xGA: 2.22,
    xGB: 1.80,
    xGAA: 0.95,
    xGAB: 1.15,
    possessionA: 62,
    possessionB: 38,
    shotsA: 15.5,
    shotsB: 9.8,
    shotsAllowedA: 7.2,
    shotsAllowedB: 12.1,
    cleanSheetA: 42,
    cleanSheetB: 33,
    bttsRateA: 40,
    bttsRateB: 50,
    recentFormA: ["W", "D", "W", "W", "W"],
    recentFormB: ["L", "W", "W", "D", "W"],
    fifaRankA: 3,
    fifaRankB: 4,
    eloRankA: 4,
    eloRankB: 5,
    squadValueA: "€1.10B",
    squadValueB: "€1.42B",
    restDaysA: 4,
    restDaysB: 5,
    fatigueA: 25,
    fatigueB: 20,
    injuriesA: ["Gavi (Knee Recovery)"],
    injuriesB: ["Harry Kane (Lower Back Spasm)"],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: ["Gavi"],
    missingKeyPlayersB: ["Harry Kane"],
    impactRatingA: "Minimal",
    impactRatingB: "Critical",
    h2hPreviousMeetings: 28,
    h2hWinsA: 11,
    h2hWinsB: 14,
    h2hDraws: 3,
    h2hGoalsA: 34,
    h2hGoalsB: 45,
    aiSummary: "The visual and spatial control numbers heavily favor Spain. Their central triangle's progressive passing output exploits England's passive midblock rest-defense posture. Combined with Harry Kane's minor lower back limitations, England's direct outlet efficiency is diminished, favoring Spain."
  },
  {
    id: "m4",
    teamA: "USA",
    teamB: "Mexico",
    teamACode: "USA",
    teamBCode: "MEX",
    date: "June 25, 2026",
    stage: "Group Stage • Group H",
    status: "UPCOMING",
    prediction: "USA Win",
    confidence: "Medium",
    probA: 48,
    probD: 28,
    probB: 24,
    venue: "SoFi Stadium, Los Angeles",
    attackA: 82,
    attackB: 78,
    defenceA: 84,
    defenceB: 80,
    midfieldA: 85,
    midfieldB: 81,
    xGA: 1.82,
    xGB: 1.30,
    xGAA: 1.05,
    xGAB: 1.40,
    possessionA: 54,
    possessionB: 46,
    shotsA: 12.5,
    shotsB: 10.2,
    shotsAllowedA: 9.8,
    shotsAllowedB: 11.5,
    cleanSheetA: 38,
    cleanSheetB: 25,
    bttsRateA: 48,
    bttsRateB: 55,
    recentFormA: ["W", "L", "W", "D", "W"],
    recentFormB: ["D", "W", "L", "L", "W"],
    fifaRankA: 14,
    fifaRankB: 17,
    eloRankA: 13,
    eloRankB: 19,
    squadValueA: "€380M",
    squadValueB: "€240M",
    restDaysA: 6,
    restDaysB: 5,
    fatigueA: 10,
    fatigueB: 15,
    injuriesA: [],
    injuriesB: ["Santiago Giménez (Foot Impact)"],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: [],
    missingKeyPlayersB: ["Santiago Giménez"],
    impactRatingA: "Minimal",
    impactRatingB: "Critical",
    h2hPreviousMeetings: 76,
    h2hWinsA: 24,
    h2hWinsB: 37,
    h2hDraws: 15,
    h2hGoalsA: 91,
    h2hGoalsB: 144,
    aiSummary: "The North American classic has shifted toward a younger, highly energetic US template. With extensive rest cycles and deep statistical efficiency on turf, USA is primed. Mexico's tactical setups suffer from transitional space leakages, amplifying the home threat."
  },
  {
    id: "m5",
    teamA: "Canada",
    teamB: "Belgium",
    teamACode: "CAN",
    teamBCode: "BEL",
    date: "June 29, 2026",
    stage: "Group Stage • Group K",
    status: "UPCOMING",
    prediction: "Belgium Win / Canada Cover",
    confidence: "Medium",
    probA: 28,
    probD: 26,
    probB: 46,
    venue: "BC Place, Vancouver",
    attackA: 80,
    attackB: 87,
    defenceA: 76,
    defenceB: 83,
    midfieldA: 79,
    midfieldB: 86,
    xGA: 1.62,
    xGB: 1.98,
    xGAA: 1.55,
    xGAB: 1.10,
    possessionA: 44,
    possessionB: 56,
    shotsA: 11.2,
    shotsB: 13.9,
    shotsAllowedA: 14.1,
    shotsAllowedB: 9.5,
    cleanSheetA: 20,
    cleanSheetB: 35,
    bttsRateA: 60,
    bttsRateB: 48,
    recentFormA: ["W", "D", "L", "W", "W"],
    recentFormB: ["W", "L", "D", "W", "L"],
    fifaRankA: 36,
    fifaRankB: 8,
    eloRankA: 28,
    eloRankB: 10,
    squadValueA: "€250M",
    squadValueB: "€620M",
    restDaysA: 5,
    restDaysB: 6,
    fatigueA: 14,
    fatigueB: 12,
    injuriesA: [],
    injuriesB: ["Kevin De Bruyne (Groin Strain)"],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: [],
    missingKeyPlayersB: ["De Bruyne"],
    impactRatingA: "Minimal",
    impactRatingB: "Critical",
    h2hPreviousMeetings: 2,
    h2hWinsA: 0,
    h2hWinsB: 2,
    h2hDraws: 0,
    h2hGoalsA: 0,
    h2hGoalsB: 4,
    aiSummary: "While Belgium retains superior structural technical quality, Kevin De Bruyne's physical groin recovery constraints restrict their progressive half-space overloading. Backed by a highly aggressive Vancouver support system, Canada's pace in wide areas can threaten, though Belgium remains favorite."
  },
  {
    id: "m6",
    teamA: "Portugal",
    teamB: "Italy",
    teamACode: "POR",
    teamBCode: "ITA",
    date: "July 2, 2026",
    stage: "Group Stage • Group L",
    status: "UPCOMING",
    prediction: "Portugal Win",
    confidence: "High",
    probA: 54,
    probD: 26,
    probB: 20,
    venue: "Lumen Field, Seattle",
    attackA: 93,
    attackB: 81,
    defenceA: 88,
    defenceB: 87,
    midfieldA: 91,
    midfieldB: 84,
    xGA: 2.40,
    xGB: 1.25,
    xGAA: 0.90,
    xGAB: 1.10,
    possessionA: 57,
    possessionB: 43,
    shotsA: 16.8,
    shotsB: 8.5,
    shotsAllowedA: 6.9,
    shotsAllowedB: 14.1,
    cleanSheetA: 46,
    cleanSheetB: 35,
    bttsRateA: 35,
    bttsRateB: 42,
    recentFormA: ["W", "W", "W", "W", "W"],
    recentFormB: ["L", "D", "W", "D", "L"],
    fifaRankA: 6,
    fifaRankB: 10,
    eloRankA: 5,
    eloRankB: 14,
    squadValueA: "€1.05B",
    squadValueB: "€720M",
    restDaysA: 5,
    restDaysB: 5,
    fatigueA: 20,
    fatigueB: 28,
    injuriesA: [],
    injuriesB: ["Alessandro Bastoni (Calf Soreness)"],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: [],
    missingKeyPlayersB: ["Bastoni"],
    impactRatingA: "Minimal",
    impactRatingB: "Moderate",
    h2hPreviousMeetings: 27,
    h2hWinsA: 6,
    h2hWinsB: 18,
    h2hDraws: 3,
    h2hGoalsA: 23,
    h2hGoalsB: 51,
    aiSummary: "Portugal is operating at peak physical cohesion and positional versatility. Italy's structural organization is constrained by key defensive absences behind, which compromises their progressive build-up and leaves them exposed to dynamic overlaps. Portugal holds a clear technical advantage."
  },
  {
    id: "m7",
    teamA: "Netherlands",
    teamB: "Senegal",
    teamACode: "NED",
    teamBCode: "SEN",
    date: "June 14, 2026",
    stage: "Group Stage • Group G",
    status: "UPCOMING",
    prediction: "Netherlands Win",
    confidence: "High",
    probA: 48,
    probD: 29,
    probB: 23,
    venue: "Arrowhead Stadium, Kansas City",
    attackA: 87,
    attackB: 80,
    defenceA: 90,
    defenceB: 82,
    midfieldA: 86,
    midfieldB: 79,
    xGA: 1.85,
    xGB: 1.15,
    xGAA: 0.95,
    xGAB: 1.35,
    possessionA: 55,
    possessionB: 45,
    shotsA: 14.1,
    shotsB: 10.2,
    shotsAllowedA: 9.8,
    shotsAllowedB: 12.4,
    cleanSheetA: 41,
    cleanSheetB: 25,
    bttsRateA: 44,
    bttsRateB: 50,
    recentFormA: ["W", "D", "W", "W", "L"],
    recentFormB: ["D", "W", "D", "W", "W"],
    fifaRankA: 8,
    fifaRankB: 18,
    eloRankA: 7,
    eloRankB: 21,
    squadValueA: "€780M",
    squadValueB: "€390M",
    restDaysA: 4,
    restDaysB: 5,
    fatigueA: 25,
    fatigueB: 22,
    injuriesA: ["Frenkie de Jong (Ankle Recovery)"],
    injuriesB: [],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: ["De Jong"],
    missingKeyPlayersB: [],
    impactRatingA: "Moderate",
    impactRatingB: "Minimal",
    h2hPreviousMeetings: 2,
    h2hWinsA: 1,
    h2hWinsB: 0,
    h2hDraws: 1,
    h2hGoalsA: 3,
    h2hGoalsB: 1,
    aiSummary: "The Dutch team displays refined possession sequences under high pressure. Senegal has robust physical power in transition, but lacks final-third tactical variations in our models, giving Netherlands a reliable structural projection to win."
  },
  {
    id: "m8",
    teamA: "Uruguay",
    teamB: "Japan",
    teamACode: "URU",
    teamBCode: "JPN",
    date: "June 26, 2026",
    stage: "Group Stage • Group E",
    status: "UPCOMING",
    prediction: "Uruguay Win",
    confidence: "Medium",
    probA: 44,
    probD: 31,
    probB: 25,
    venue: "Hard Rock Stadium, Miami",
    attackA: 89,
    attackB: 85,
    defenceA: 85,
    defenceB: 83,
    midfieldA: 88,
    midfieldB: 86,
    xGA: 2.10,
    xGB: 1.65,
    xGAA: 1.15,
    xGAB: 1.28,
    possessionA: 52,
    possessionB: 48,
    shotsA: 15.3,
    shotsB: 12.8,
    shotsAllowedA: 11.2,
    shotsAllowedB: 14.5,
    cleanSheetA: 32,
    cleanSheetB: 29,
    bttsRateA: 55,
    bttsRateB: 48,
    recentFormA: ["W", "L", "W", "W", "D"],
    recentFormB: ["W", "W", "D", "L", "W"],
    fifaRankA: 12,
    fifaRankB: 15,
    eloRankA: 9,
    eloRankB: 16,
    squadValueA: "€540M",
    squadValueB: "€320M",
    restDaysA: 5,
    restDaysB: 5,
    fatigueA: 19,
    fatigueB: 17,
    injuriesA: [],
    injuriesB: ["Takehiro Tomiyasu (Calf)"],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: [],
    missingKeyPlayersB: ["Tomiyasu"],
    impactRatingA: "Minimal",
    impactRatingB: "Moderate",
    h2hPreviousMeetings: 8,
    h2hWinsA: 4,
    h2hWinsB: 2,
    h2hDraws: 2,
    h2hGoalsA: 15,
    h2hGoalsB: 11,
    aiSummary: "Uruguay's elite intensity under Bielsa clashes with Japan’s highly coordinated press. The model flags a high probability of central transition errors from Japan, which Uruguay’s rapid vertical progressives can convert effectively."
  },
  {
    id: "m9",
    teamA: "Croatia",
    teamB: "Morocco",
    teamACode: "CRO",
    teamBCode: "MAR",
    date: "June 27, 2026",
    stage: "Group Stage • Group H",
    status: "UPCOMING",
    prediction: "Morocco Win",
    confidence: "Medium",
    probA: 28,
    probD: 32,
    probB: 40,
    venue: "Levi's Stadium, San Francisco Bay Area",
    attackA: 81,
    attackB: 86,
    defenceA: 84,
    defenceB: 89,
    midfieldA: 89,
    midfieldB: 87,
    xGA: 1.25,
    xGB: 1.95,
    xGAA: 1.30,
    xGAB: 0.80,
    possessionA: 54,
    possessionB: 46,
    shotsA: 10.4,
    shotsB: 14.8,
    shotsAllowedA: 13.9,
    shotsAllowedB: 8.5,
    cleanSheetA: 28,
    cleanSheetB: 48,
    bttsRateA: 36,
    bttsRateB: 32,
    recentFormA: ["D", "L", "W", "D", "W"],
    recentFormB: ["W", "W", "W", "D", "W"],
    fifaRankA: 10,
    fifaRankB: 13,
    eloRankA: 11,
    eloRankB: 10,
    squadValueA: "€380M",
    squadValueB: "€410M",
    restDaysA: 6,
    restDaysB: 6,
    fatigueA: 35,
    fatigueB: 15,
    injuriesA: [],
    injuriesB: [],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: [],
    missingKeyPlayersB: [],
    impactRatingA: "Minimal",
    impactRatingB: "Minimal",
    h2hPreviousMeetings: 3,
    h2hWinsA: 1,
    h2hWinsB: 1,
    h2hDraws: 1,
    h2hGoalsA: 2,
    h2hGoalsB: 2,
    aiSummary: "Morocco's athletic fullback pairing and high fatigue-mitigation index counter Croatia's veteran possession retention. Our tactical simulations point heavily to Morocco seizing full-third transition opportunities."
  },
  {
    id: "m10",
    teamA: "Brazil",
    teamB: "Argentina",
    teamACode: "BRA",
    teamBCode: "ARG",
    date: "July 05, 2026",
    stage: "Quarter Final",
    status: "UPCOMING",
    prediction: "Brazil Win",
    confidence: "High",
    probA: 45,
    probD: 35,
    probB: 20,
    venue: "MetLife Stadium, New Jersey",
    attackA: 95,
    attackB: 93,
    defenceA: 90,
    defenceB: 91,
    midfieldA: 92,
    midfieldB: 93,
    xGA: 2.30,
    xGB: 2.15,
    xGAA: 0.90,
    xGAB: 0.95,
    possessionA: 51,
    possessionB: 49,
    shotsA: 15.5,
    shotsB: 14.1,
    shotsAllowedA: 10.0,
    shotsAllowedB: 11.2,
    cleanSheetA: 40,
    cleanSheetB: 38,
    bttsRateA: 48,
    bttsRateB: 46,
    recentFormA: ["W", "W", "W", "D", "W"],
    recentFormB: ["W", "W", "W", "W", "D"],
    fifaRankA: 5,
    fifaRankB: 1,
    eloRankA: 3,
    eloRankB: 1,
    squadValueA: "€1.25B",
    squadValueB: "€950M",
    restDaysA: 4,
    restDaysB: 4,
    fatigueA: 22,
    fatigueB: 24,
    injuriesA: [],
    injuriesB: [],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: [],
    missingKeyPlayersB: [],
    impactRatingA: "Minimal",
    impactRatingB: "Minimal",
    h2hPreviousMeetings: 110,
    h2hWinsA: 46,
    h2hWinsB: 41,
    h2hDraws: 23,
    h2hGoalsA: 165,
    h2hGoalsB: 160,
    aiSummary: "The ultimate Superclásico configured inside the Quarter Final stage. Simulated over 50,000 matches, Brazil's recovery metrics in rest-defense give them a slim but notable structural advantage over Argentina's aging midfield spine."
  },
  {
    id: "m11",
    teamA: "France",
    teamB: "Spain",
    teamACode: "FRA",
    teamBCode: "ESP",
    date: "July 09, 2026",
    stage: "Semi Final",
    status: "UPCOMING",
    prediction: "France Win",
    confidence: "High",
    probA: 49,
    probD: 28,
    probB: 23,
    venue: "AT&T Stadium, Dallas",
    attackA: 96,
    attackB: 91,
    defenceA: 91,
    defenceB: 89,
    midfieldA: 90,
    midfieldB: 96,
    xGA: 2.25,
    xGB: 1.88,
    xGAA: 0.92,
    xGAB: 1.12,
    possessionA: 46,
    possessionB: 54,
    shotsA: 16.4,
    shotsB: 13.9,
    shotsAllowedA: 11.5,
    shotsAllowedB: 9.8,
    cleanSheetA: 44,
    cleanSheetB: 33,
    bttsRateA: 41,
    bttsRateB: 45,
    recentFormA: ["W", "D", "W", "L", "W"],
    recentFormB: ["W", "W", "W", "W", "D"],
    fifaRankA: 2,
    fifaRankB: 3,
    eloRankA: 2,
    eloRankB: 4,
    squadValueA: "€1.35B",
    squadValueB: "€1.05B",
    restDaysA: 5,
    restDaysB: 5,
    fatigueA: 14,
    fatigueB: 19,
    injuriesA: [],
    injuriesB: [],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: [],
    missingKeyPlayersB: [],
    impactRatingA: "Minimal",
    impactRatingB: "Minimal",
    h2hPreviousMeetings: 36,
    h2hWinsA: 13,
    h2hWinsB: 16,
    h2hDraws: 7,
    h2hGoalsA: 39,
    h2hGoalsB: 49,
    aiSummary: "Spain will dominate midfield control metrics, but France's extreme vertical efficiency through Mbappé represents a critical matchup failure for Spain's high defensive line. Simulations lean heavily to France in transitional moments."
  },
  {
    id: "m12",
    teamA: "Argentina",
    teamB: "England",
    teamACode: "ARG",
    teamBCode: "ENG",
    date: "July 19, 2026",
    stage: "Final",
    status: "UPCOMING",
    prediction: "Argentina Win",
    confidence: "High",
    probA: 55,
    probD: 25,
    probB: 20,
    venue: "MetLife Stadium, New Jersey",
    attackA: 94,
    attackB: 90,
    defenceA: 92,
    defenceB: 86,
    midfieldA: 92,
    midfieldB: 91,
    xGA: 2.10,
    xGB: 1.70,
    xGAA: 0.85,
    xGAB: 1.25,
    possessionA: 54,
    possessionB: 46,
    shotsA: 14.5,
    shotsB: 11.2,
    shotsAllowedA: 8.8,
    shotsAllowedB: 13.9,
    cleanSheetA: 48,
    cleanSheetB: 31,
    bttsRateA: 38,
    bttsRateB: 42,
    recentFormA: ["W", "W", "W", "W", "D"],
    recentFormB: ["W", "D", "W", "W", "L"],
    fifaRankA: 1,
    fifaRankB: 4,
    eloRankA: 1,
    eloRankB: 3,
    squadValueA: "€950M",
    squadValueB: "€1.20B",
    restDaysA: 7,
    restDaysB: 7,
    fatigueA: 10,
    fatigueB: 18,
    injuriesA: [],
    injuriesB: [],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: [],
    missingKeyPlayersB: [],
    impactRatingA: "Minimal",
    impactRatingB: "Minimal",
    h2hPreviousMeetings: 14,
    h2hWinsA: 5,
    h2hWinsB: 6,
    h2hDraws: 3,
    h2hGoalsA: 18,
    h2hGoalsB: 21,
    aiSummary: "The ultimate tournament projection. Argentina's structural compactness in key moments combined with deep knockout experience outperforms an England team struggling with squad spinal fatigue, rendering a high probability of a championship win for Argentina."
  },
  {
    id: "m13",
    teamA: "Colombia",
    teamB: "Belgium",
    teamACode: "COL",
    teamBCode: "BEL",
    date: "July 01, 2026",
    stage: "Round of 16",
    status: "UPCOMING",
    prediction: "Belgium Win",
    confidence: "Medium",
    probA: 31,
    probD: 30,
    probB: 39,
    venue: "BC Place, Vancouver",
    attackA: 85,
    attackB: 88,
    defenceA: 83,
    defenceB: 84,
    midfieldA: 84,
    midfieldB: 87,
    xGA: 1.55,
    xGB: 1.78,
    xGAA: 1.35,
    xGAB: 1.18,
    possessionA: 47,
    possessionB: 53,
    shotsA: 11.8,
    shotsB: 13.9,
    shotsAllowedA: 12.8,
    shotsAllowedB: 10.4,
    cleanSheetA: 30,
    cleanSheetB: 36,
    bttsRateA: 52,
    bttsRateB: 49,
    recentFormA: ["D", "W", "W", "L", "W"],
    recentFormB: ["W", "D", "L", "W", "D"],
    fifaRankA: 14,
    fifaRankB: 7,
    eloRankA: 15,
    eloRankB: 8,
    squadValueA: "€280M",
    squadValueB: "€640M",
    restDaysA: 5,
    restDaysB: 5,
    fatigueA: 22,
    fatigueB: 26,
    injuriesA: [],
    injuriesB: [],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: [],
    missingKeyPlayersB: [],
    impactRatingA: "Minimal",
    impactRatingB: "Minimal",
    h2hPreviousMeetings: 4,
    h2hWinsA: 1,
    h2hWinsB: 2,
    h2hDraws: 1,
    h2hGoalsA: 4,
    h2hGoalsB: 6,
    aiSummary: "An intriguing vertical style clash. Colombia's high-pressing energy presents threats, but Belgium's progressive efficiency in breaking press lines through De Bruyne represents the core deciding asset according to 50,000 simulations."
  },
  {
    id: "m14",
    teamA: "Denmark",
    teamB: "Mexico",
    teamACode: "DEN",
    teamBCode: "MEX",
    date: "June 30, 2026",
    stage: "Round of 32",
    status: "UPCOMING",
    prediction: "Mexico Win",
    confidence: "High",
    probA: 34,
    probD: 28,
    probB: 38,
    venue: "NRG Stadium, Houston",
    attackA: 82,
    attackB: 85,
    defenceA: 84,
    defenceB: 83,
    midfieldA: 84,
    midfieldB: 86,
    xGA: 1.40,
    xGB: 1.62,
    xGAA: 1.30,
    xGAB: 1.20,
    possessionA: 49,
    possessionB: 51,
    shotsA: 11.2,
    shotsB: 13.5,
    shotsAllowedA: 12.1,
    shotsAllowedB: 11.9,
    cleanSheetA: 33,
    cleanSheetB: 35,
    bttsRateA: 50,
    bttsRateB: 53,
    recentFormA: ["D", "W", "L", "W", "D"],
    recentFormB: ["W", "D", "W", "L", "W"],
    fifaRankA: 17,
    fifaRankB: 16,
    eloRankA: 18,
    eloRankB: 15,
    squadValueA: "€310M",
    squadValueB: "€290M",
    restDaysA: 4,
    restDaysB: 5,
    fatigueA: 20,
    fatigueB: 15,
    injuriesA: [],
    injuriesB: [],
    suspensionsA: [],
    suspensionsB: [],
    missingKeyPlayersA: [],
    missingKeyPlayersB: [],
    impactRatingA: "Minimal",
    impactRatingB: "Minimal",
    h2hPreviousMeetings: 6,
    h2hWinsA: 2,
    h2hWinsB: 2,
    h2hDraws: 2,
    h2hGoalsA: 8,
    h2hGoalsB: 8,
    aiSummary: "The home crowd environment gives Mexico an amplified mental and physical edge. Denmark’s defensive rest organization is highly vulnerable to progressive cutbacks, pointing the probability lean toward Mexico."
  }
];

export const MOCK_TROPHY_PROBABILITIES: TrophyProbability[] = [
  {
    rank: 1,
    name: "Argentina",
    code: "ARG",
    winProbabilityPercent: 18.4,
    confidence: "High",
    recentForm: ["W", "W", "W", "W", "D"],
    tournamentStrength: 96,
    attackRating: 92,
    defenceRating: 91,
    midfieldRating: 93,
    gkRating: 89,
    squadDepth: 93,
    avgAge: 27.6,
    marketValue: "€950M",
    coach: "Lionel Scaloni",
    coachRating: 97,
    last10Wins: 8,
    last10Draws: 1,
    last10Losses: 1,
    last10GoalsScored: 24,
    last10GoalsConceded: 6,
    likelyPath: {
      groupStage: "Group C Winner",
      roundOf32: "vs Denmark (Group D Runner-up)",
      roundOf16: "vs Belgium (Group K Winner)",
      quarterFinal: "vs England (QF)",
      semiFinal: "vs Spain (SF)",
      final: "vs Brazil (Final)"
    }
  },
  {
    rank: 2,
    name: "Brazil",
    code: "BRA",
    winProbabilityPercent: 16.1,
    confidence: "High",
    recentForm: ["W", "W", "W", "D", "W"],
    tournamentStrength: 94,
    attackRating: 94,
    defenceRating: 89,
    midfieldRating: 91,
    gkRating: 92,
    squadDepth: 95,
    avgAge: 26.4,
    marketValue: "€1.25B",
    coach: "Dorival Júnior",
    coachRating: 88,
    last10Wins: 7,
    last10Draws: 2,
    last10Losses: 1,
    last10GoalsScored: 26,
    last10GoalsConceded: 8,
    likelyPath: {
      groupStage: "Group A Winner",
      roundOf32: "vs Sweden (Group B Runner-up)",
      roundOf16: "vs Germany (Round of 16)",
      quarterFinal: "vs Portugal (Quarter Final)",
      semiFinal: "vs France (Semi Final)",
      final: "vs Argentina (Final)"
    }
  },
  {
    rank: 3,
    name: "France",
    code: "FRA",
    winProbabilityPercent: 14.8,
    confidence: "High",
    recentForm: ["W", "D", "W", "L", "W"],
    tournamentStrength: 93,
    attackRating: 95,
    defenceRating: 90,
    midfieldRating: 89,
    gkRating: 88,
    squadDepth: 97,
    avgAge: 25.8,
    marketValue: "€1.35B",
    coach: "Didier Deschamps",
    coachRating: 92,
    last10Wins: 6,
    last10Draws: 2,
    last10Losses: 2,
    last10GoalsScored: 22,
    last10GoalsConceded: 9,
    likelyPath: {
      groupStage: "Group B Winner",
      roundOf32: "vs Ukraine (Group A Runner-up)",
      roundOf16: "vs Italy (Round of 16)",
      quarterFinal: "vs Netherlands (Quarter Final)",
      semiFinal: "vs Brazil (Semi Final)",
      final: "vs Argentina (Final)"
    }
  },
  {
    rank: 4,
    name: "Spain",
    code: "ESP",
    winProbabilityPercent: 12.2,
    confidence: "High",
    recentForm: ["W", "D", "W", "W", "W"],
    tournamentStrength: 92,
    attackRating: 90,
    defenceRating: 88,
    midfieldRating: 95,
    gkRating: 86,
    squadDepth: 90,
    avgAge: 24.8,
    marketValue: "€1.10B",
    coach: "Luis de la Fuente",
    coachRating: 94,
    last10Wins: 8,
    last10Draws: 1,
    last10Losses: 1,
    last10GoalsScored: 25,
    last10GoalsConceded: 7,
    likelyPath: {
      groupStage: "Group F Winner",
      roundOf32: "vs Chile (Group E Runner-up)",
      roundOf16: "vs Uruguay (Round of 16)",
      quarterFinal: "vs USA (Quarter Final)",
      semiFinal: "vs Argentina (Semi Final)",
      final: "vs Brazil (Final)"
    }
  },
  {
    rank: 5,
    name: "England",
    code: "ENG",
    winProbabilityPercent: 9.8,
    confidence: "Medium",
    recentForm: ["L", "W", "W", "D", "W"],
    tournamentStrength: 89,
    attackRating: 89,
    defenceRating: 85,
    midfieldRating: 92,
    gkRating: 84,
    squadDepth: 96,
    avgAge: 26.2,
    marketValue: "€1.42B",
    coach: "Thomas Tuchel",
    coachRating: 91,
    last10Wins: 5,
    last10Draws: 3,
    last10Losses: 2,
    last10GoalsScored: 18,
    last10GoalsConceded: 10,
    likelyPath: {
      groupStage: "Group E Winner",
      roundOf32: "vs Austria (Group F Runner-up)",
      roundOf16: "vs Switzerland (Round of 16)",
      quarterFinal: "vs Argentina (Quarter Final)",
      semiFinal: "vs Spain (Semi Final)",
      final: "vs Brazil (Final)"
    }
  },
  {
    rank: 6,
    name: "Portugal",
    code: "POR",
    winProbabilityPercent: 8.5,
    confidence: "High",
    recentForm: ["W", "W", "W", "W", "W"],
    tournamentStrength: 90,
    attackRating: 93,
    defenceRating: 88,
    midfieldRating: 91,
    gkRating: 87,
    squadDepth: 94,
    avgAge: 26.9,
    marketValue: "€1.05B",
    coach: "Roberto Martínez",
    coachRating: 85,
    last10Wins: 8,
    last10Draws: 1,
    last10Losses: 1,
    last10GoalsScored: 27,
    last10GoalsConceded: 8,
    likelyPath: {
      groupStage: "Group L Winner",
      roundOf32: "vs South Korea (Group K Runner-up)",
      roundOf16: "vs Croatia (Round of 16)",
      quarterFinal: "vs Brazil (Quarter Final)",
      semiFinal: "vs France (Semi Final)",
      final: "vs Argentina (Final)"
    }
  }
];

export const MOCK_INTELLIGENCE: IntelligenceInsight[] = [
  {
    id: "int1",
    type: "Most Improved Team",
    team: "USA",
    details: "Expected goals conceded dropped by 34% inside the last six months, paired with extreme vertical speed outliers under Thomas Tuchel's structural lessons.",
    secondaryMetric: "-34% xGA Decline",
    analyst: "Tactical Desk, London",
    explanation: "Under the latest technical refinements, the US squad has drastically improved its rest-defense. High athletic capacity allows them to retreat and compact spaces within seconds, limiting central shot creation channels. This quantitative adjustment converts a historically unstable, high-variance squad into a robust defensive organization capable of deep bracket runs."
  },
  {
    id: "int2",
    type: "Best Attack",
    team: "France",
    details: "Averaging 2.65 Expected Goals (xG) per 90, driven by the most progressive acceleration metrics in deep half-spaces.",
    secondaryMetric: "2.65 xG / 90 min",
    analyst: "Data Operations, Paris",
    explanation: "France's structural attacking efficiency relies on explosive isolation patterns on both wings. Progressive ball carry metrics reveal that they bypass defensive blocks faster than any other team in Europe. With deep squad options allowing constant athletic rotation, France maintains high output throughout 90 minutes with zero degradation."
  },
  {
    id: "int3",
    type: "Best Defence",
    team: "Argentina",
    details: "Registry confirms only 4 professional goals conceded in their last 12 competitive matches. Opponents averaged an empty 0.62 xG per game.",
    secondaryMetric: "0.62 xG Allowed",
    analyst: "Analytical Director, Buenos Aires",
    explanation: "Argentina's success is rooted in aggressive rest-defense positioning. By compressing central space early in opponent build-ups, they deny passing lanes before transition risks materialize. High tactical discipline keeps their central center-backs shielded, minimizing high-quality chances against them."
  },
  {
    id: "int4",
    type: "Dark Horse",
    team: "Ecuador",
    details: "Unmatched high-altitude cardiovascular baseline metrics matching supreme central structural solidity in ELO ratings.",
    secondaryMetric: "+148 ELO points",
    analyst: "Global Scouting, Quito",
    explanation: "Ecuador possesses a unique high-intensity physical core that excels in double-pivot setups. The tactical data highlights high physical recovery rates, enabling them to sustain an intense high-press for full matches. If matched against possession-heavy European transition templates, Ecuador's pacing and physical disruptions present major tactical obstacles."
  },
  {
    id: "int5",
    type: "Biggest Upset Candidate",
    team: "Germany",
    details: "High squad fatigue indexes combined with severe spatial vulnerabilities in defensive response to rapid transitions.",
    secondaryMetric: "1.45 xGA Vulnerability",
    analyst: "Strategic Advisor, Berlin",
    explanation: "Germany's tactical setup is vulnerable to vertical transitions. When their fullbacks advance, spatial metrics show large gaps on the wings that are easily exploited. Aging center-backs lack recovery speed under counter-attacks, making them a prime candidate for early upsets against dynamic low-block transition sides."
  },
  {
    id: "int6",
    type: "Most Underrated Squad",
    team: "Denmark",
    details: "Consistent upper-decile rankings in set-piece expected goals (xG) and spatial midfield recycling rates.",
    secondaryMetric: "42% Set-piece xG Share",
    analyst: "Data Analyst, Copenhagen",
    explanation: "Denmark runs a highly sophisticated, deterministic strategy based on planned dead-ball operations. Their physical profile suits crowded box overloads, while their midfield recycling rates ensure constant territorial recovery. They are highly efficient at winning tight games without needing open-field brilliant plays."
  },
  {
    id: "int7",
    type: "Best Emerging Player",
    team: "Lamine Yamal (Spain)",
    details: " Outperforming all traditional age bracket progress curves in high-pressure creative metrics and progressive carries.",
    secondaryMetric: "6.8 Progressive Carries/90",
    analyst: "Director of Youth Scouting, Madrid",
    explanation: "Yamal's statistical profile shows extreme maturity in progressive carries and key passing decisions. Under pressure, his turnover index is exceptionally low, representing elite spatial awareness. He remains Spain's premium offensive creator, generating immediate territorial advantages."
  },
  {
    id: "int8",
    type: "Most Difficult Group",
    team: "Group L (Portugal, Italy, Senegal, Japan)",
    details: "The highest aggregate ELO concentration in World Cup history. Expect severe positional friction grids.",
    secondaryMetric: "1894 Avg Group ELO",
    analyst: "Tournament Design, Munich",
    explanation: "Group L represents an unprecedented tactical bottleneck. Senegal and Japan hold high physical and structural baselines that directly disrupt Portugal and Italy's offensive schemes. Every single point in this bracket is heavily contested, making fatigue management and structural discipline critical survival elements."
  }
];

export const MOCK_ACCURACY_STATS = {
  totalPredictions: 412,
  correctPredictions: 326,
  accuracyPercentage: 79.1,
  roi: 18.4, // Return on Intelligence metric :)
  tournamentAccuracy: [
    { tournament: "Copa América 2024", accuracy: 82.4, size: 32 },
    { tournament: "Euro 2024", accuracy: 80.7, size: 51 },
    { tournament: "WC Qualifiers 2025", accuracy: 78.5, size: 218 },
    { tournament: "Nations League 2025", accuracy: 77.1, size: 111 }
  ],
  calibration: [
    { modelConfidenceRange: "90% - 100%", actualAccuracy: 92.4, volume: 53 },
    { modelConfidenceRange: "80% - 90%", actualAccuracy: 84.1, volume: 112 },
    { modelConfidenceRange: "70% - 80%", actualAccuracy: 74.8, volume: 145 },
    { modelConfidenceRange: "50% - 70%", actualAccuracy: 61.2, volume: 102 }
  ]
};
